import controllers.FilesCreator;
import models.*;

import java.util.List;
import java.util.ArrayList;

public class Scanner {
	private final static String NULL = "NULL";
	private final static String WHITESPACE = "WHITESPACE";
	private final static String ID = "ID";
	private final static String NUMBER = "NUMBER";
	private final static String PLUS = "PLUS";
	private final static String MINUS = "MINUS";
	private final static String TIMES = "TIMES";
	private final static String DIV = "DIV";
	private final static String LPAREN = "LPAREN";
	private final static String RPAREN = "RPAREN";

	private static String scan(String token){
		if(token.equals("ws")){
			return WHITESPACE;
		}
		if(token.equals("id")){
			return ID;
		}
		if(token.equals("number")){
			return NUMBER;
		}
		if(token.equals("+")){
			return PLUS;
		}
		if(token.equals("-")){
			return MINUS;
		}
		if(token.equals("*")){
			return TIMES;
		}
		if(token.equals("/")){
			return DIV;
		}
		if(token.equals("(")){
			return LPAREN;
		}
		if(token.equals(")")){
			return RPAREN;
		}
		return NULL;
	}

	public static void main(String[] args) {
		if (args.length == 0){
			System.out.println("Te falto ingresar un archivo en los argumentos");
			System.out.println("EJEMPLO: java Scanner file");
			return;
		}
		System.out.println("===> Scanner.java");

		// Obtener Automata 
		NFA automata = megaAutomata(); 
		
		// Leer contenido del archivo 
		ArrayList<String> fileContent = FilesCreator.readFileContent(args[0]); 
		ArrayList<String> results = new ArrayList<String>(); 
		ArrayList<String> actions = new ArrayList<String>(); 

		String lexema = "", idDetected = ""; 
		for (String string : fileContent) { 
		    for (int i = 0; i < string.length(); i++) {
		        char c = string.charAt(i); 
		        int ascii = (int)c; 
		        String[] result = automata.simulateMega(ascii+"");
				System.out.println(automata.simulateTest(ascii+""));
		        // Vamos a evaluar si el id detectado esta vacio
		        if(idDetected.length() == 0){ 
		        	idDetected = result[1];
		        	lexema += c;
		        	if(result[1].equals("ERROR LEXICO")){
		        		results.add("[" + c + " - Token: " + result[1] + "]\n");
		        		actions.add("[" + c + " - Token Action: " + scan(result[1]) + "]\n");
		        	    idDetected = "";
		        	    lexema = "";
		        	}
		        }
		        else if(idDetected.equals(result[1])) lexema += c;
		        else{ // Si ya no es igual entonces se detiene
		            results.add("[" + lexema + " - Token: " + idDetected + "]\n");
		        	actions.add("[" + lexema + " - Token Action: " + scan(idDetected) + "]\n");
		            // Resetear el id Detectado
		        	idDetected = result[1];
		            lexema = c + "";
		        }
		    } 
		} 
		if(!FilesCreator.createFileTokens(results, "docs/outputFile") || !FilesCreator.createFileTokens(actions, "docs/outputFileActions")){
		    System.out.println("Error a la hora de crear el output :(");
		    return;
		}
	}

	private static NFA megaAutomata() { 
		// Automata Generado 
		State initialState = new State(0, Types.Initial);
		List<State> finalStates = new ArrayList<State>();
		finalStates.add(new State("25", Types.Final));
		finalStates.add(new State("481", Types.Final));
		finalStates.add(new State("765", Types.Final));
		finalStates.add(new State("769", Types.Final));
		finalStates.add(new State("773", Types.Final));
		finalStates.add(new State("777", Types.Final));
		finalStates.add(new State("781", Types.Final));
		finalStates.add(new State("785", Types.Final));
		finalStates.add(new State("789", Types.Final));
		List<State> states = new ArrayList<State>();
		states.add(new State("25", Types.Final));
		states.add(new State("481", Types.Final));
		states.add(new State("765", Types.Final));
		states.add(new State("769", Types.Final));
		states.add(new State("773", Types.Final));
		states.add(new State("777", Types.Final));
		states.add(new State("781", Types.Final));
		states.add(new State("785", Types.Final));
		states.add(new State("789", Types.Final));
		List<Transition> transitions = new ArrayList<Transition>();
		transitions.add(new Transition(new Symbol("32", "ws"), new State("1", Types.Transition), new State("2", Types.Transition)));
		transitions.add(new Transition(new Symbol("9", "ws"), new State("3", Types.Transition), new State("4", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("5", Types.Transition), new State("1", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("5", Types.Transition), new State("3", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("2", Types.Transition), new State("6", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("4", Types.Transition), new State("6", Types.Transition)));
		transitions.add(new Transition(new Symbol("10", "ws"), new State("7", Types.Transition), new State("8", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("9", Types.Initial), new State("5", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("9", Types.Initial), new State("7", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("6", Types.Transition), new State("10", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("8", Types.Transition), new State("10", Types.Transition)));
		transitions.add(new Transition(new Symbol("32"), new State("11", Types.Transition), new State("12", Types.Transition)));
		transitions.add(new Transition(new Symbol("9"), new State("13", Types.Transition), new State("14", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("15", Types.Transition), new State("11", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("15", Types.Transition), new State("13", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("12", Types.Transition), new State("16", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("14", Types.Transition), new State("16", Types.Transition)));
		transitions.add(new Transition(new Symbol("10"), new State("17", Types.Transition), new State("18", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("19", Types.Transition), new State("15", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("19", Types.Transition), new State("17", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("16", Types.Transition), new State("20", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("18", Types.Transition), new State("20", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("20", Types.Transition), new State("19", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("22", Types.Transition), new State("23", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("22", Types.Transition), new State("19", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("20", Types.Transition), new State("23", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("10", Types.Transition), new State("22", Types.Transition)));
		transitions.add(new Transition(new Symbol("#ws", "ws"), new State("24", Types.Transition), new State("25", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("23", Types.Transition), new State("24", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("9", Types.Initial)));
		transitions.add(new Transition(new Symbol("65", "id"), new State("26", Types.Transition), new State("27", Types.Transition)));
		transitions.add(new Transition(new Symbol("66", "id"), new State("28", Types.Transition), new State("29", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("30", Types.Transition), new State("26", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("30", Types.Transition), new State("28", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("27", Types.Transition), new State("31", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("29", Types.Transition), new State("31", Types.Transition)));
		transitions.add(new Transition(new Symbol("67", "id"), new State("32", Types.Transition), new State("33", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("34", Types.Transition), new State("30", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("34", Types.Transition), new State("32", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("31", Types.Transition), new State("35", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("33", Types.Transition), new State("35", Types.Transition)));
		transitions.add(new Transition(new Symbol("68", "id"), new State("36", Types.Transition), new State("37", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("38", Types.Transition), new State("34", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("38", Types.Transition), new State("36", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("35", Types.Transition), new State("39", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("37", Types.Transition), new State("39", Types.Transition)));
		transitions.add(new Transition(new Symbol("69", "id"), new State("40", Types.Transition), new State("41", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("42", Types.Transition), new State("38", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("42", Types.Transition), new State("40", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("39", Types.Transition), new State("43", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("41", Types.Transition), new State("43", Types.Transition)));
		transitions.add(new Transition(new Symbol("70", "id"), new State("44", Types.Transition), new State("45", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("46", Types.Transition), new State("42", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("46", Types.Transition), new State("44", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("43", Types.Transition), new State("47", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("45", Types.Transition), new State("47", Types.Transition)));
		transitions.add(new Transition(new Symbol("71", "id"), new State("48", Types.Transition), new State("49", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("50", Types.Transition), new State("46", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("50", Types.Transition), new State("48", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("47", Types.Transition), new State("51", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("49", Types.Transition), new State("51", Types.Transition)));
		transitions.add(new Transition(new Symbol("72", "id"), new State("52", Types.Transition), new State("53", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("54", Types.Transition), new State("50", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("54", Types.Transition), new State("52", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("51", Types.Transition), new State("55", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("53", Types.Transition), new State("55", Types.Transition)));
		transitions.add(new Transition(new Symbol("73", "id"), new State("56", Types.Transition), new State("57", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("58", Types.Transition), new State("54", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("58", Types.Transition), new State("56", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("55", Types.Transition), new State("59", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("57", Types.Transition), new State("59", Types.Transition)));
		transitions.add(new Transition(new Symbol("74", "id"), new State("60", Types.Transition), new State("61", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("62", Types.Transition), new State("58", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("62", Types.Transition), new State("60", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("59", Types.Transition), new State("63", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("61", Types.Transition), new State("63", Types.Transition)));
		transitions.add(new Transition(new Symbol("75", "id"), new State("64", Types.Transition), new State("65", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("66", Types.Transition), new State("62", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("66", Types.Transition), new State("64", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("63", Types.Transition), new State("67", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("65", Types.Transition), new State("67", Types.Transition)));
		transitions.add(new Transition(new Symbol("76", "id"), new State("68", Types.Transition), new State("69", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("70", Types.Transition), new State("66", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("70", Types.Transition), new State("68", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("67", Types.Transition), new State("71", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("69", Types.Transition), new State("71", Types.Transition)));
		transitions.add(new Transition(new Symbol("77", "id"), new State("72", Types.Transition), new State("73", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("74", Types.Transition), new State("70", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("74", Types.Transition), new State("72", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("71", Types.Transition), new State("75", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("73", Types.Transition), new State("75", Types.Transition)));
		transitions.add(new Transition(new Symbol("78", "id"), new State("76", Types.Transition), new State("77", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("78", Types.Transition), new State("74", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("78", Types.Transition), new State("76", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("75", Types.Transition), new State("79", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("77", Types.Transition), new State("79", Types.Transition)));
		transitions.add(new Transition(new Symbol("79", "id"), new State("80", Types.Transition), new State("81", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("82", Types.Transition), new State("78", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("82", Types.Transition), new State("80", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("79", Types.Transition), new State("83", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("81", Types.Transition), new State("83", Types.Transition)));
		transitions.add(new Transition(new Symbol("80", "id"), new State("84", Types.Transition), new State("85", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("86", Types.Transition), new State("82", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("86", Types.Transition), new State("84", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("83", Types.Transition), new State("87", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("85", Types.Transition), new State("87", Types.Transition)));
		transitions.add(new Transition(new Symbol("81", "id"), new State("88", Types.Transition), new State("89", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("90", Types.Transition), new State("86", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("90", Types.Transition), new State("88", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("87", Types.Transition), new State("91", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("89", Types.Transition), new State("91", Types.Transition)));
		transitions.add(new Transition(new Symbol("82", "id"), new State("92", Types.Transition), new State("93", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("94", Types.Transition), new State("90", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("94", Types.Transition), new State("92", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("91", Types.Transition), new State("95", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("93", Types.Transition), new State("95", Types.Transition)));
		transitions.add(new Transition(new Symbol("83", "id"), new State("96", Types.Transition), new State("97", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("98", Types.Transition), new State("94", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("98", Types.Transition), new State("96", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("95", Types.Transition), new State("99", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("97", Types.Transition), new State("99", Types.Transition)));
		transitions.add(new Transition(new Symbol("84", "id"), new State("100", Types.Transition), new State("101", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("102", Types.Transition), new State("98", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("102", Types.Transition), new State("100", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("99", Types.Transition), new State("103", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("101", Types.Transition), new State("103", Types.Transition)));
		transitions.add(new Transition(new Symbol("85", "id"), new State("104", Types.Transition), new State("105", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("106", Types.Transition), new State("102", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("106", Types.Transition), new State("104", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("103", Types.Transition), new State("107", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("105", Types.Transition), new State("107", Types.Transition)));
		transitions.add(new Transition(new Symbol("86", "id"), new State("108", Types.Transition), new State("109", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("110", Types.Transition), new State("106", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("110", Types.Transition), new State("108", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("107", Types.Transition), new State("111", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("109", Types.Transition), new State("111", Types.Transition)));
		transitions.add(new Transition(new Symbol("87", "id"), new State("112", Types.Transition), new State("113", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("114", Types.Transition), new State("110", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("114", Types.Transition), new State("112", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("111", Types.Transition), new State("115", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("113", Types.Transition), new State("115", Types.Transition)));
		transitions.add(new Transition(new Symbol("88", "id"), new State("116", Types.Transition), new State("117", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("118", Types.Transition), new State("114", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("118", Types.Transition), new State("116", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("115", Types.Transition), new State("119", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("117", Types.Transition), new State("119", Types.Transition)));
		transitions.add(new Transition(new Symbol("89", "id"), new State("120", Types.Transition), new State("121", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("122", Types.Transition), new State("118", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("122", Types.Transition), new State("120", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("119", Types.Transition), new State("123", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("121", Types.Transition), new State("123", Types.Transition)));
		transitions.add(new Transition(new Symbol("90", "id"), new State("124", Types.Transition), new State("125", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("126", Types.Transition), new State("122", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("126", Types.Transition), new State("124", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("123", Types.Transition), new State("127", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("125", Types.Transition), new State("127", Types.Transition)));
		transitions.add(new Transition(new Symbol("97", "id"), new State("128", Types.Transition), new State("129", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("130", Types.Transition), new State("126", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("130", Types.Transition), new State("128", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("127", Types.Transition), new State("131", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("129", Types.Transition), new State("131", Types.Transition)));
		transitions.add(new Transition(new Symbol("98", "id"), new State("132", Types.Transition), new State("133", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("134", Types.Transition), new State("130", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("134", Types.Transition), new State("132", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("131", Types.Transition), new State("135", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("133", Types.Transition), new State("135", Types.Transition)));
		transitions.add(new Transition(new Symbol("99", "id"), new State("136", Types.Transition), new State("137", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("138", Types.Transition), new State("134", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("138", Types.Transition), new State("136", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("135", Types.Transition), new State("139", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("137", Types.Transition), new State("139", Types.Transition)));
		transitions.add(new Transition(new Symbol("100", "id"), new State("140", Types.Transition), new State("141", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("142", Types.Transition), new State("138", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("142", Types.Transition), new State("140", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("139", Types.Transition), new State("143", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("141", Types.Transition), new State("143", Types.Transition)));
		transitions.add(new Transition(new Symbol("101", "id"), new State("144", Types.Transition), new State("145", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("146", Types.Transition), new State("142", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("146", Types.Transition), new State("144", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("143", Types.Transition), new State("147", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("145", Types.Transition), new State("147", Types.Transition)));
		transitions.add(new Transition(new Symbol("102", "id"), new State("148", Types.Transition), new State("149", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("150", Types.Transition), new State("146", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("150", Types.Transition), new State("148", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("147", Types.Transition), new State("151", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("149", Types.Transition), new State("151", Types.Transition)));
		transitions.add(new Transition(new Symbol("103", "id"), new State("152", Types.Transition), new State("153", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("154", Types.Transition), new State("150", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("154", Types.Transition), new State("152", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("151", Types.Transition), new State("155", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("153", Types.Transition), new State("155", Types.Transition)));
		transitions.add(new Transition(new Symbol("104", "id"), new State("156", Types.Transition), new State("157", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("158", Types.Transition), new State("154", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("158", Types.Transition), new State("156", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("155", Types.Transition), new State("159", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("157", Types.Transition), new State("159", Types.Transition)));
		transitions.add(new Transition(new Symbol("105", "id"), new State("160", Types.Transition), new State("161", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("162", Types.Transition), new State("158", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("162", Types.Transition), new State("160", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("159", Types.Transition), new State("163", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("161", Types.Transition), new State("163", Types.Transition)));
		transitions.add(new Transition(new Symbol("106", "id"), new State("164", Types.Transition), new State("165", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("166", Types.Transition), new State("162", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("166", Types.Transition), new State("164", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("163", Types.Transition), new State("167", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("165", Types.Transition), new State("167", Types.Transition)));
		transitions.add(new Transition(new Symbol("107", "id"), new State("168", Types.Transition), new State("169", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("170", Types.Transition), new State("166", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("170", Types.Transition), new State("168", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("167", Types.Transition), new State("171", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("169", Types.Transition), new State("171", Types.Transition)));
		transitions.add(new Transition(new Symbol("108", "id"), new State("172", Types.Transition), new State("173", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("174", Types.Transition), new State("170", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("174", Types.Transition), new State("172", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("171", Types.Transition), new State("175", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("173", Types.Transition), new State("175", Types.Transition)));
		transitions.add(new Transition(new Symbol("109", "id"), new State("176", Types.Transition), new State("177", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("178", Types.Transition), new State("174", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("178", Types.Transition), new State("176", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("175", Types.Transition), new State("179", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("177", Types.Transition), new State("179", Types.Transition)));
		transitions.add(new Transition(new Symbol("110", "id"), new State("180", Types.Transition), new State("181", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("182", Types.Transition), new State("178", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("182", Types.Transition), new State("180", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("179", Types.Transition), new State("183", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("181", Types.Transition), new State("183", Types.Transition)));
		transitions.add(new Transition(new Symbol("111", "id"), new State("184", Types.Transition), new State("185", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("186", Types.Transition), new State("182", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("186", Types.Transition), new State("184", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("183", Types.Transition), new State("187", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("185", Types.Transition), new State("187", Types.Transition)));
		transitions.add(new Transition(new Symbol("112", "id"), new State("188", Types.Transition), new State("189", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("190", Types.Transition), new State("186", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("190", Types.Transition), new State("188", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("187", Types.Transition), new State("191", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("189", Types.Transition), new State("191", Types.Transition)));
		transitions.add(new Transition(new Symbol("113", "id"), new State("192", Types.Transition), new State("193", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("194", Types.Transition), new State("190", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("194", Types.Transition), new State("192", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("191", Types.Transition), new State("195", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("193", Types.Transition), new State("195", Types.Transition)));
		transitions.add(new Transition(new Symbol("114", "id"), new State("196", Types.Transition), new State("197", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("198", Types.Transition), new State("194", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("198", Types.Transition), new State("196", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("195", Types.Transition), new State("199", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("197", Types.Transition), new State("199", Types.Transition)));
		transitions.add(new Transition(new Symbol("115", "id"), new State("200", Types.Transition), new State("201", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("202", Types.Transition), new State("198", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("202", Types.Transition), new State("200", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("199", Types.Transition), new State("203", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("201", Types.Transition), new State("203", Types.Transition)));
		transitions.add(new Transition(new Symbol("116", "id"), new State("204", Types.Transition), new State("205", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("206", Types.Transition), new State("202", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("206", Types.Transition), new State("204", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("203", Types.Transition), new State("207", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("205", Types.Transition), new State("207", Types.Transition)));
		transitions.add(new Transition(new Symbol("117", "id"), new State("208", Types.Transition), new State("209", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("210", Types.Transition), new State("206", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("210", Types.Transition), new State("208", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("207", Types.Transition), new State("211", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("209", Types.Transition), new State("211", Types.Transition)));
		transitions.add(new Transition(new Symbol("118", "id"), new State("212", Types.Transition), new State("213", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("214", Types.Transition), new State("210", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("214", Types.Transition), new State("212", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("211", Types.Transition), new State("215", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("213", Types.Transition), new State("215", Types.Transition)));
		transitions.add(new Transition(new Symbol("119", "id"), new State("216", Types.Transition), new State("217", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("218", Types.Transition), new State("214", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("218", Types.Transition), new State("216", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("215", Types.Transition), new State("219", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("217", Types.Transition), new State("219", Types.Transition)));
		transitions.add(new Transition(new Symbol("120", "id"), new State("220", Types.Transition), new State("221", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("222", Types.Transition), new State("218", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("222", Types.Transition), new State("220", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("219", Types.Transition), new State("223", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("221", Types.Transition), new State("223", Types.Transition)));
		transitions.add(new Transition(new Symbol("121", "id"), new State("224", Types.Transition), new State("225", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("226", Types.Transition), new State("222", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("226", Types.Transition), new State("224", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("223", Types.Transition), new State("227", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("225", Types.Transition), new State("227", Types.Transition)));
		transitions.add(new Transition(new Symbol("122", "id"), new State("228", Types.Transition), new State("229", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("230", Types.Initial), new State("226", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("230", Types.Initial), new State("228", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("227", Types.Transition), new State("231", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("229", Types.Transition), new State("231", Types.Transition)));
		transitions.add(new Transition(new Symbol("65", "id"), new State("232", Types.Transition), new State("233", Types.Transition)));
		transitions.add(new Transition(new Symbol("66", "id"), new State("234", Types.Transition), new State("235", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("236", Types.Transition), new State("232", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("236", Types.Transition), new State("234", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("233", Types.Transition), new State("237", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("235", Types.Transition), new State("237", Types.Transition)));
		transitions.add(new Transition(new Symbol("67", "id"), new State("238", Types.Transition), new State("239", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("240", Types.Transition), new State("236", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("240", Types.Transition), new State("238", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("237", Types.Transition), new State("241", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("239", Types.Transition), new State("241", Types.Transition)));
		transitions.add(new Transition(new Symbol("68", "id"), new State("242", Types.Transition), new State("243", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("244", Types.Transition), new State("240", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("244", Types.Transition), new State("242", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("241", Types.Transition), new State("245", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("243", Types.Transition), new State("245", Types.Transition)));
		transitions.add(new Transition(new Symbol("69", "id"), new State("246", Types.Transition), new State("247", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("248", Types.Transition), new State("244", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("248", Types.Transition), new State("246", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("245", Types.Transition), new State("249", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("247", Types.Transition), new State("249", Types.Transition)));
		transitions.add(new Transition(new Symbol("70", "id"), new State("250", Types.Transition), new State("251", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("252", Types.Transition), new State("248", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("252", Types.Transition), new State("250", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("249", Types.Transition), new State("253", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("251", Types.Transition), new State("253", Types.Transition)));
		transitions.add(new Transition(new Symbol("71", "id"), new State("254", Types.Transition), new State("255", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("256", Types.Transition), new State("252", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("256", Types.Transition), new State("254", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("253", Types.Transition), new State("257", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("255", Types.Transition), new State("257", Types.Transition)));
		transitions.add(new Transition(new Symbol("72", "id"), new State("258", Types.Transition), new State("259", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("260", Types.Transition), new State("256", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("260", Types.Transition), new State("258", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("257", Types.Transition), new State("261", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("259", Types.Transition), new State("261", Types.Transition)));
		transitions.add(new Transition(new Symbol("73", "id"), new State("262", Types.Transition), new State("263", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("264", Types.Transition), new State("260", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("264", Types.Transition), new State("262", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("261", Types.Transition), new State("265", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("263", Types.Transition), new State("265", Types.Transition)));
		transitions.add(new Transition(new Symbol("74", "id"), new State("266", Types.Transition), new State("267", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("268", Types.Transition), new State("264", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("268", Types.Transition), new State("266", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("265", Types.Transition), new State("269", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("267", Types.Transition), new State("269", Types.Transition)));
		transitions.add(new Transition(new Symbol("75", "id"), new State("270", Types.Transition), new State("271", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("272", Types.Transition), new State("268", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("272", Types.Transition), new State("270", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("269", Types.Transition), new State("273", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("271", Types.Transition), new State("273", Types.Transition)));
		transitions.add(new Transition(new Symbol("76", "id"), new State("274", Types.Transition), new State("275", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("276", Types.Transition), new State("272", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("276", Types.Transition), new State("274", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("273", Types.Transition), new State("277", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("275", Types.Transition), new State("277", Types.Transition)));
		transitions.add(new Transition(new Symbol("77", "id"), new State("278", Types.Transition), new State("279", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("280", Types.Transition), new State("276", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("280", Types.Transition), new State("278", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("277", Types.Transition), new State("281", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("279", Types.Transition), new State("281", Types.Transition)));
		transitions.add(new Transition(new Symbol("78", "id"), new State("282", Types.Transition), new State("283", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("284", Types.Transition), new State("280", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("284", Types.Transition), new State("282", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("281", Types.Transition), new State("285", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("283", Types.Transition), new State("285", Types.Transition)));
		transitions.add(new Transition(new Symbol("79", "id"), new State("286", Types.Transition), new State("287", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("288", Types.Transition), new State("284", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("288", Types.Transition), new State("286", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("285", Types.Transition), new State("289", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("287", Types.Transition), new State("289", Types.Transition)));
		transitions.add(new Transition(new Symbol("80", "id"), new State("290", Types.Transition), new State("291", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("292", Types.Transition), new State("288", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("292", Types.Transition), new State("290", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("289", Types.Transition), new State("293", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("291", Types.Transition), new State("293", Types.Transition)));
		transitions.add(new Transition(new Symbol("81", "id"), new State("294", Types.Transition), new State("295", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("296", Types.Transition), new State("292", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("296", Types.Transition), new State("294", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("293", Types.Transition), new State("297", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("295", Types.Transition), new State("297", Types.Transition)));
		transitions.add(new Transition(new Symbol("82", "id"), new State("298", Types.Transition), new State("299", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("300", Types.Transition), new State("296", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("300", Types.Transition), new State("298", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("297", Types.Transition), new State("301", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("299", Types.Transition), new State("301", Types.Transition)));
		transitions.add(new Transition(new Symbol("83", "id"), new State("302", Types.Transition), new State("303", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("304", Types.Transition), new State("300", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("304", Types.Transition), new State("302", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("301", Types.Transition), new State("305", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("303", Types.Transition), new State("305", Types.Transition)));
		transitions.add(new Transition(new Symbol("84", "id"), new State("306", Types.Transition), new State("307", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("308", Types.Transition), new State("304", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("308", Types.Transition), new State("306", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("305", Types.Transition), new State("309", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("307", Types.Transition), new State("309", Types.Transition)));
		transitions.add(new Transition(new Symbol("85", "id"), new State("310", Types.Transition), new State("311", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("312", Types.Transition), new State("308", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("312", Types.Transition), new State("310", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("309", Types.Transition), new State("313", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("311", Types.Transition), new State("313", Types.Transition)));
		transitions.add(new Transition(new Symbol("86", "id"), new State("314", Types.Transition), new State("315", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("316", Types.Transition), new State("312", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("316", Types.Transition), new State("314", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("313", Types.Transition), new State("317", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("315", Types.Transition), new State("317", Types.Transition)));
		transitions.add(new Transition(new Symbol("87", "id"), new State("318", Types.Transition), new State("319", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("320", Types.Transition), new State("316", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("320", Types.Transition), new State("318", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("317", Types.Transition), new State("321", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("319", Types.Transition), new State("321", Types.Transition)));
		transitions.add(new Transition(new Symbol("88", "id"), new State("322", Types.Transition), new State("323", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("324", Types.Transition), new State("320", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("324", Types.Transition), new State("322", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("321", Types.Transition), new State("325", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("323", Types.Transition), new State("325", Types.Transition)));
		transitions.add(new Transition(new Symbol("89", "id"), new State("326", Types.Transition), new State("327", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("328", Types.Transition), new State("324", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("328", Types.Transition), new State("326", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("325", Types.Transition), new State("329", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("327", Types.Transition), new State("329", Types.Transition)));
		transitions.add(new Transition(new Symbol("90", "id"), new State("330", Types.Transition), new State("331", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("332", Types.Transition), new State("328", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("332", Types.Transition), new State("330", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("329", Types.Transition), new State("333", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("331", Types.Transition), new State("333", Types.Transition)));
		transitions.add(new Transition(new Symbol("97", "id"), new State("334", Types.Transition), new State("335", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("336", Types.Transition), new State("332", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("336", Types.Transition), new State("334", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("333", Types.Transition), new State("337", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("335", Types.Transition), new State("337", Types.Transition)));
		transitions.add(new Transition(new Symbol("98", "id"), new State("338", Types.Transition), new State("339", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("340", Types.Transition), new State("336", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("340", Types.Transition), new State("338", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("337", Types.Transition), new State("341", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("339", Types.Transition), new State("341", Types.Transition)));
		transitions.add(new Transition(new Symbol("99", "id"), new State("342", Types.Transition), new State("343", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("344", Types.Transition), new State("340", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("344", Types.Transition), new State("342", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("341", Types.Transition), new State("345", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("343", Types.Transition), new State("345", Types.Transition)));
		transitions.add(new Transition(new Symbol("100", "id"), new State("346", Types.Transition), new State("347", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("348", Types.Transition), new State("344", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("348", Types.Transition), new State("346", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("345", Types.Transition), new State("349", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("347", Types.Transition), new State("349", Types.Transition)));
		transitions.add(new Transition(new Symbol("101", "id"), new State("350", Types.Transition), new State("351", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("352", Types.Transition), new State("348", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("352", Types.Transition), new State("350", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("349", Types.Transition), new State("353", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("351", Types.Transition), new State("353", Types.Transition)));
		transitions.add(new Transition(new Symbol("102", "id"), new State("354", Types.Transition), new State("355", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("356", Types.Transition), new State("352", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("356", Types.Transition), new State("354", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("353", Types.Transition), new State("357", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("355", Types.Transition), new State("357", Types.Transition)));
		transitions.add(new Transition(new Symbol("103", "id"), new State("358", Types.Transition), new State("359", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("360", Types.Transition), new State("356", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("360", Types.Transition), new State("358", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("357", Types.Transition), new State("361", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("359", Types.Transition), new State("361", Types.Transition)));
		transitions.add(new Transition(new Symbol("104", "id"), new State("362", Types.Transition), new State("363", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("364", Types.Transition), new State("360", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("364", Types.Transition), new State("362", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("361", Types.Transition), new State("365", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("363", Types.Transition), new State("365", Types.Transition)));
		transitions.add(new Transition(new Symbol("105", "id"), new State("366", Types.Transition), new State("367", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("368", Types.Transition), new State("364", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("368", Types.Transition), new State("366", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("365", Types.Transition), new State("369", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("367", Types.Transition), new State("369", Types.Transition)));
		transitions.add(new Transition(new Symbol("106", "id"), new State("370", Types.Transition), new State("371", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("372", Types.Transition), new State("368", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("372", Types.Transition), new State("370", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("369", Types.Transition), new State("373", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("371", Types.Transition), new State("373", Types.Transition)));
		transitions.add(new Transition(new Symbol("107", "id"), new State("374", Types.Transition), new State("375", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("376", Types.Transition), new State("372", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("376", Types.Transition), new State("374", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("373", Types.Transition), new State("377", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("375", Types.Transition), new State("377", Types.Transition)));
		transitions.add(new Transition(new Symbol("108", "id"), new State("378", Types.Transition), new State("379", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("380", Types.Transition), new State("376", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("380", Types.Transition), new State("378", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("377", Types.Transition), new State("381", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("379", Types.Transition), new State("381", Types.Transition)));
		transitions.add(new Transition(new Symbol("109", "id"), new State("382", Types.Transition), new State("383", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("384", Types.Transition), new State("380", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("384", Types.Transition), new State("382", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("381", Types.Transition), new State("385", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("383", Types.Transition), new State("385", Types.Transition)));
		transitions.add(new Transition(new Symbol("110", "id"), new State("386", Types.Transition), new State("387", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("388", Types.Transition), new State("384", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("388", Types.Transition), new State("386", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("385", Types.Transition), new State("389", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("387", Types.Transition), new State("389", Types.Transition)));
		transitions.add(new Transition(new Symbol("111", "id"), new State("390", Types.Transition), new State("391", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("392", Types.Transition), new State("388", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("392", Types.Transition), new State("390", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("389", Types.Transition), new State("393", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("391", Types.Transition), new State("393", Types.Transition)));
		transitions.add(new Transition(new Symbol("112", "id"), new State("394", Types.Transition), new State("395", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("396", Types.Transition), new State("392", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("396", Types.Transition), new State("394", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("393", Types.Transition), new State("397", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("395", Types.Transition), new State("397", Types.Transition)));
		transitions.add(new Transition(new Symbol("113", "id"), new State("398", Types.Transition), new State("399", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("400", Types.Transition), new State("396", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("400", Types.Transition), new State("398", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("397", Types.Transition), new State("401", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("399", Types.Transition), new State("401", Types.Transition)));
		transitions.add(new Transition(new Symbol("114", "id"), new State("402", Types.Transition), new State("403", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("404", Types.Transition), new State("400", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("404", Types.Transition), new State("402", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("401", Types.Transition), new State("405", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("403", Types.Transition), new State("405", Types.Transition)));
		transitions.add(new Transition(new Symbol("115", "id"), new State("406", Types.Transition), new State("407", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("408", Types.Transition), new State("404", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("408", Types.Transition), new State("406", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("405", Types.Transition), new State("409", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("407", Types.Transition), new State("409", Types.Transition)));
		transitions.add(new Transition(new Symbol("116", "id"), new State("410", Types.Transition), new State("411", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("412", Types.Transition), new State("408", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("412", Types.Transition), new State("410", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("409", Types.Transition), new State("413", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("411", Types.Transition), new State("413", Types.Transition)));
		transitions.add(new Transition(new Symbol("117", "id"), new State("414", Types.Transition), new State("415", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("416", Types.Transition), new State("412", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("416", Types.Transition), new State("414", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("413", Types.Transition), new State("417", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("415", Types.Transition), new State("417", Types.Transition)));
		transitions.add(new Transition(new Symbol("118", "id"), new State("418", Types.Transition), new State("419", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("420", Types.Transition), new State("416", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("420", Types.Transition), new State("418", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("417", Types.Transition), new State("421", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("419", Types.Transition), new State("421", Types.Transition)));
		transitions.add(new Transition(new Symbol("119", "id"), new State("422", Types.Transition), new State("423", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("424", Types.Transition), new State("420", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("424", Types.Transition), new State("422", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("421", Types.Transition), new State("425", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("423", Types.Transition), new State("425", Types.Transition)));
		transitions.add(new Transition(new Symbol("120", "id"), new State("426", Types.Transition), new State("427", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("428", Types.Transition), new State("424", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("428", Types.Transition), new State("426", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("425", Types.Transition), new State("429", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("427", Types.Transition), new State("429", Types.Transition)));
		transitions.add(new Transition(new Symbol("121", "id"), new State("430", Types.Transition), new State("431", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("432", Types.Transition), new State("428", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("432", Types.Transition), new State("430", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("429", Types.Transition), new State("433", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("431", Types.Transition), new State("433", Types.Transition)));
		transitions.add(new Transition(new Symbol("122", "id"), new State("434", Types.Transition), new State("435", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("436", Types.Transition), new State("432", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("436", Types.Transition), new State("434", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("433", Types.Transition), new State("437", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("435", Types.Transition), new State("437", Types.Transition)));
		transitions.add(new Transition(new Symbol("48", "id"), new State("438", Types.Transition), new State("439", Types.Transition)));
		transitions.add(new Transition(new Symbol("49", "id"), new State("440", Types.Transition), new State("441", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("442", Types.Transition), new State("438", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("442", Types.Transition), new State("440", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("439", Types.Transition), new State("443", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("441", Types.Transition), new State("443", Types.Transition)));
		transitions.add(new Transition(new Symbol("50", "id"), new State("444", Types.Transition), new State("445", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("446", Types.Transition), new State("442", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("446", Types.Transition), new State("444", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("443", Types.Transition), new State("447", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("445", Types.Transition), new State("447", Types.Transition)));
		transitions.add(new Transition(new Symbol("51", "id"), new State("448", Types.Transition), new State("449", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("450", Types.Transition), new State("446", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("450", Types.Transition), new State("448", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("447", Types.Transition), new State("451", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("449", Types.Transition), new State("451", Types.Transition)));
		transitions.add(new Transition(new Symbol("52", "id"), new State("452", Types.Transition), new State("453", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("454", Types.Transition), new State("450", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("454", Types.Transition), new State("452", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("451", Types.Transition), new State("455", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("453", Types.Transition), new State("455", Types.Transition)));
		transitions.add(new Transition(new Symbol("53", "id"), new State("456", Types.Transition), new State("457", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("458", Types.Transition), new State("454", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("458", Types.Transition), new State("456", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("455", Types.Transition), new State("459", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("457", Types.Transition), new State("459", Types.Transition)));
		transitions.add(new Transition(new Symbol("54", "id"), new State("460", Types.Transition), new State("461", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("462", Types.Transition), new State("458", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("462", Types.Transition), new State("460", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("459", Types.Transition), new State("463", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("461", Types.Transition), new State("463", Types.Transition)));
		transitions.add(new Transition(new Symbol("55", "id"), new State("464", Types.Transition), new State("465", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("466", Types.Transition), new State("462", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("466", Types.Transition), new State("464", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("463", Types.Transition), new State("467", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("465", Types.Transition), new State("467", Types.Transition)));
		transitions.add(new Transition(new Symbol("56", "id"), new State("468", Types.Transition), new State("469", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("470", Types.Transition), new State("466", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("470", Types.Transition), new State("468", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("467", Types.Transition), new State("471", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("469", Types.Transition), new State("471", Types.Transition)));
		transitions.add(new Transition(new Symbol("57", "id"), new State("472", Types.Transition), new State("473", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("474", Types.Transition), new State("470", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("474", Types.Transition), new State("472", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("471", Types.Transition), new State("475", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("473", Types.Transition), new State("475", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("476", Types.Transition), new State("436", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("476", Types.Transition), new State("474", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("437", Types.Transition), new State("477", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("475", Types.Transition), new State("477", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("477", Types.Transition), new State("476", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("478", Types.Transition), new State("479", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("478", Types.Transition), new State("476", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("477", Types.Transition), new State("479", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("231", Types.Transition), new State("478", Types.Transition)));
		transitions.add(new Transition(new Symbol("#id", "id"), new State("480", Types.Transition), new State("481", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("479", Types.Transition), new State("480", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("230", Types.Initial)));
		transitions.add(new Transition(new Symbol(".", "number"), new State("666", Types.Initial), new State("667", Types.Transition)));
		transitions.add(new Transition(new Symbol("69", "number"), new State("668", Types.Transition), new State("669", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("670", Types.Transition), new State("671", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("672", Types.Transition), new State("668", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("672", Types.Transition), new State("670", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("669", Types.Transition), new State("673", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("671", Types.Transition), new State("673", Types.Transition)));
		transitions.add(new Transition(new Symbol("48", "number"), new State("674", Types.Transition), new State("675", Types.Transition)));
		transitions.add(new Transition(new Symbol("49", "number"), new State("676", Types.Transition), new State("677", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("678", Types.Transition), new State("674", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("678", Types.Transition), new State("676", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("675", Types.Transition), new State("679", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("677", Types.Transition), new State("679", Types.Transition)));
		transitions.add(new Transition(new Symbol("50", "number"), new State("680", Types.Transition), new State("681", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("682", Types.Transition), new State("678", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("682", Types.Transition), new State("680", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("679", Types.Transition), new State("683", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("681", Types.Transition), new State("683", Types.Transition)));
		transitions.add(new Transition(new Symbol("51", "number"), new State("684", Types.Transition), new State("685", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("686", Types.Transition), new State("682", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("686", Types.Transition), new State("684", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("683", Types.Transition), new State("687", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("685", Types.Transition), new State("687", Types.Transition)));
		transitions.add(new Transition(new Symbol("52", "number"), new State("688", Types.Transition), new State("689", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("690", Types.Transition), new State("686", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("690", Types.Transition), new State("688", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("687", Types.Transition), new State("691", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("689", Types.Transition), new State("691", Types.Transition)));
		transitions.add(new Transition(new Symbol("53", "number"), new State("692", Types.Transition), new State("693", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("694", Types.Transition), new State("690", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("694", Types.Transition), new State("692", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("691", Types.Transition), new State("695", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("693", Types.Transition), new State("695", Types.Transition)));
		transitions.add(new Transition(new Symbol("54", "number"), new State("696", Types.Transition), new State("697", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("698", Types.Transition), new State("694", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("698", Types.Transition), new State("696", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("695", Types.Transition), new State("699", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("697", Types.Transition), new State("699", Types.Transition)));
		transitions.add(new Transition(new Symbol("55", "number"), new State("700", Types.Transition), new State("701", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("702", Types.Transition), new State("698", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("702", Types.Transition), new State("700", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("699", Types.Transition), new State("703", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("701", Types.Transition), new State("703", Types.Transition)));
		transitions.add(new Transition(new Symbol("56", "number"), new State("704", Types.Transition), new State("705", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("706", Types.Transition), new State("702", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("706", Types.Transition), new State("704", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("703", Types.Transition), new State("707", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("705", Types.Transition), new State("707", Types.Transition)));
		transitions.add(new Transition(new Symbol("57", "number"), new State("708", Types.Transition), new State("709", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("710", Types.Transition), new State("706", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("710", Types.Transition), new State("708", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("707", Types.Transition), new State("711", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("709", Types.Transition), new State("711", Types.Transition)));
		transitions.add(new Transition(new Symbol("48"), new State("712", Types.Transition), new State("713", Types.Transition)));
		transitions.add(new Transition(new Symbol("49"), new State("714", Types.Transition), new State("715", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("716", Types.Transition), new State("712", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("716", Types.Transition), new State("714", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("713", Types.Transition), new State("717", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("715", Types.Transition), new State("717", Types.Transition)));
		transitions.add(new Transition(new Symbol("50"), new State("718", Types.Transition), new State("719", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("720", Types.Transition), new State("716", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("720", Types.Transition), new State("718", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("717", Types.Transition), new State("721", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("719", Types.Transition), new State("721", Types.Transition)));
		transitions.add(new Transition(new Symbol("51"), new State("722", Types.Transition), new State("723", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("724", Types.Transition), new State("720", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("724", Types.Transition), new State("722", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("721", Types.Transition), new State("725", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("723", Types.Transition), new State("725", Types.Transition)));
		transitions.add(new Transition(new Symbol("52"), new State("726", Types.Transition), new State("727", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("728", Types.Transition), new State("724", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("728", Types.Transition), new State("726", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("725", Types.Transition), new State("729", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("727", Types.Transition), new State("729", Types.Transition)));
		transitions.add(new Transition(new Symbol("53"), new State("730", Types.Transition), new State("731", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("732", Types.Transition), new State("728", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("732", Types.Transition), new State("730", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("729", Types.Transition), new State("733", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("731", Types.Transition), new State("733", Types.Transition)));
		transitions.add(new Transition(new Symbol("54"), new State("734", Types.Transition), new State("735", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("736", Types.Transition), new State("732", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("736", Types.Transition), new State("734", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("733", Types.Transition), new State("737", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("735", Types.Transition), new State("737", Types.Transition)));
		transitions.add(new Transition(new Symbol("55"), new State("738", Types.Transition), new State("739", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("740", Types.Transition), new State("736", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("740", Types.Transition), new State("738", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("737", Types.Transition), new State("741", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("739", Types.Transition), new State("741", Types.Transition)));
		transitions.add(new Transition(new Symbol("56"), new State("742", Types.Transition), new State("743", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("744", Types.Transition), new State("740", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("744", Types.Transition), new State("742", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("741", Types.Transition), new State("745", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("743", Types.Transition), new State("745", Types.Transition)));
		transitions.add(new Transition(new Symbol("57"), new State("746", Types.Transition), new State("747", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("748", Types.Transition), new State("744", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("748", Types.Transition), new State("746", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("745", Types.Transition), new State("749", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("747", Types.Transition), new State("749", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("749", Types.Transition), new State("748", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("758", Types.Transition), new State("759", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("758", Types.Transition), new State("748", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("749", Types.Transition), new State("759", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("711", Types.Transition), new State("758", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("673", Types.Transition), new State("710", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("760", Types.Transition), new State("761", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("762", Types.Transition), new State("672", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("762", Types.Transition), new State("760", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("759", Types.Transition), new State("763", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("761", Types.Transition), new State("763", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("667", Types.Transition), new State("762", Types.Transition)));
		transitions.add(new Transition(new Symbol("#number", "number"), new State("764", Types.Transition), new State("765", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("763", Types.Transition), new State("764", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("666", Types.Initial)));
		transitions.add(new Transition(new Symbol("43", "+"), new State("766", Types.Initial), new State("767", Types.Transition)));
		transitions.add(new Transition(new Symbol("#+", "+"), new State("768", Types.Transition), new State("769", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("767", Types.Transition), new State("768", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("766", Types.Initial)));
		transitions.add(new Transition(new Symbol("45", "-"), new State("770", Types.Initial), new State("771", Types.Transition)));
		transitions.add(new Transition(new Symbol("#-", "-"), new State("772", Types.Transition), new State("773", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("771", Types.Transition), new State("772", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("770", Types.Initial)));
		transitions.add(new Transition(new Symbol("42", "*"), new State("774", Types.Initial), new State("775", Types.Transition)));
		transitions.add(new Transition(new Symbol("#*", "*"), new State("776", Types.Transition), new State("777", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("775", Types.Transition), new State("776", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("774", Types.Initial)));
		transitions.add(new Transition(new Symbol("47", "/"), new State("778", Types.Initial), new State("779", Types.Transition)));
		transitions.add(new Transition(new Symbol("#/", "/"), new State("780", Types.Transition), new State("781", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("779", Types.Transition), new State("780", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("778", Types.Initial)));
		transitions.add(new Transition(new Symbol("40", "("), new State("782", Types.Initial), new State("783", Types.Transition)));
		transitions.add(new Transition(new Symbol("#(", "("), new State("784", Types.Transition), new State("785", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("783", Types.Transition), new State("784", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("782", Types.Initial)));
		transitions.add(new Transition(new Symbol("41", ")"), new State("786", Types.Initial), new State("787", Types.Transition)));
		transitions.add(new Transition(new Symbol("#)", ")"), new State("788", Types.Transition), new State("789", Types.Final)));
		transitions.add(new Transition(new Symbol("€"), new State("787", Types.Transition), new State("788", Types.Transition)));
		transitions.add(new Transition(new Symbol("€"), new State("0", Types.Initial), new State("786", Types.Initial)));
		return new NFA(initialState, finalStates, states, transitions);
	}
}
